### ISSUE TITLE
Change Tab order for Edit2 / Icon not shown in 10.0.19044

### ISSUE THREAD

**Issue by megabugman** [jNizM/master-password#2]
nice script. I like the dark mode. It took me a while to figure out how this works.

consider fixing this:
I. Edit2 tab order should changed. When pressing Tab with Edit1 focused the cursor should jump to Edit2
II. I've changed 10.0.22000 to 10.0.19044 now the icon is shown correctly in my Windows Version.

**Comment by jNizM** [comment]
Fixed in:
- https://github.com/jNizM/master-password/commit/4afd910d47eab30d282b1f3546f9bf764b1eb8ba
- https://github.com/jNizM/master-password/commit/ac21fa5b089ee304b80de25f3542a34baa73f3b5
